### PR TITLE
Change dcc / antivirus plugins

### PR DESCRIPTION
**Pull request by c-rosenberg**
- Antivirus: Next upstream should be tried on any error. Current Upstream should be set to fail in that case
- Antivirus: While scanning mime_parts only is great for caching scanned attachment digests, sometimes it's useful to scan the textparts (e.g. ClamAV Unofficial Sanesecurity ...).
- DCC: separate socket and server configuration to make use of the upstreams feature.

### CODE REVIEW

**Comment by vstakhov** [comment]
I'm sorry but I cannot accept the antivirus module changes: you've broken the backward compatibility by removing `attachments_only` option. Is it possible to preserve this option and its meaning?

**Comment by c-rosenberg** [comment]
Sorry, forgot to push the workaround for attachments_only

**Comment by vstakhov** [comment]
Could you also fix luacheck warnings please?

**Comment by vstakhov** [comment]
Looks good to me, thank you very much!

**Pull request merged**
