### PR TITLE
[Minor] Prevent duplicate rows from being inserted into neural traini…

### PR DESCRIPTION
**Pull request by cpragadeesh**
I looked into ordered set vs regular set in redis and I don't think its worth maintaining a rank for each of the training vectors. Please let me know if ordered sets have a benefit that I am not aware of and I'll get the code changed.

### CODE REVIEW

**Comment by vstakhov** [comment]
We were thinking about storing emphasis in priority (e.g. classification errors). However, upon more thinking I believe the same thing could be achieved by using just a structure inside Redis vectors (e.g. serialising them using message pack and add extra fields if needed) and not using Redis `Z` structures as they require much more maintenance indeed.

**Comment by vstakhov** [comment]
Oh, and it has broken the tests.

**Comment by cpragadeesh** [comment]
> Oh, and it has broken the tests.

Yeah, i'll get it fixed

**Comment by vstakhov** [comment]
Fixing this test will be tricky... It uses the same learning vectors all the time.

**Comment by vstakhov** [comment]
I've almost fixed manual training, but PCA version still fails... Probably I'll just disable it for now. Manual training is not familiar to me, so please fix it if possible.

**Pull request merged**
