### PR TITLE
[Minor] Add "rpmsg" to bad_extensions

### PR DESCRIPTION
**Pull request by twesterhever**
Rationale: https://dshield.org/forums/diary/Be+careful+with+RPMSG+files/28292

### CODE REVIEW

**Comment by vstakhov** [comment]
Hum, I'm not sure if the proposed change is valid. `rpmsg` is used by Microsoft products for encrypted content and I've seen it quite often in clear HAM (even within my personal mailbox).

**Comment by twesterhever** [comment]
Oh, I see. For me, it was the opposite - I never saw these in legitimate mails, only in phishing attempts.

Feel free to close this PR, or drop me a line if I should lower the score.

**Comment by citrin** [comment]
I can confirm that is actively used in ham.

**Comment by twesterhever** [comment]
All right, closing this. Thank you for your replies and advice!

**Pull request closed without merging**
