### PR TITLE
[Fix] Further fix for i386 compilation

### PR DESCRIPTION
**Pull request by a16bitsysop**
Compiles and passes tests on alpine Linux

### CODE REVIEW

**Comment by a16bitsysop** [comment]
Is `SET(HAVE_AVX2 0)` in the right place?

**Comment by vstakhov** [comment]
I have another idea, as we have AVX2 in C intriniscs which will work and AVX2 in assembly code which will be broken. So we need to distinguish these two things. I'd better just check for architecture in the `chacha` dispatcher.

**Comment by vstakhov** [comment]
Can it now be compiled on x86?

**Comment by a16bitsysop** [comment]
Will check later, thanks.

**Comment by a16bitsysop** [comment]
The new commit still has the rax error:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/533563#L957

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/27238/diffs

**Comment by a16bitsysop** [comment]
I added this patch:
```
--- a/src/libcryptobox/cryptobox.c
+++ b/src/libcryptobox/cryptobox.c
@@ -146,7 +146,7 @@
                __asm__ volatile ("pcmpeqq %xmm0, %xmm0");
                break;
 #endif
-#ifdef HAVE_SSE42
+#if defined HAVE_SSE42 && defined(__x86_64__)
        case CPUID_SSE42:
                __asm__ volatile ("pushq %rax\n"
                                "xorq %rax, %rax\n"
```

and then it compiles, but segfaults on the run-test, which was the pre patch behaviour.

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/533814#L1659

**Comment by a16bitsysop** [comment]
With this version it builds and passes tests on alpine:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/533830

**Pull request merged**
