### PR TITLE
[Feature] Multimap: support adding map values as extra options

### PR DESCRIPTION
**Pull request by fatalbanana**

### CODE REVIEW

**Comment by vstakhov** [comment]
Hum, the PR name does not correspond to what it does. Could you please clarify?

**Comment by fatalbanana** [comment]
The idea is to provide an alternative use for the values in the maps: where-in they're added as extra options, rather than yielded as symbols.

So one could yield something like:
```MAP_RCPT (1.0) [example.com, Cool Description]```
rather than:
```MAP_RCPT_COOL_DESCRIPTION (1.0) [example.com]```

**Comment by vstakhov** [comment]
Maybe we should set a single option like `example.com=Cool Description`? I'm thinking from Clickhouse analytics point.

**Comment by vstakhov** [comment]
Added this but we might need to think about it one more time...

**Pull request merged**
