### PR TITLE
Add Czech stop words

### PR DESCRIPTION
**Pull request by Disassembler0**
This PR adds Czech stop words as suggested in #3156.

If the diacritics need to be `\u` escaped, please let me know.

### CODE REVIEW

**Comment by vstakhov** [comment]
It looks good but the general rule is to avoid words that can clash with other languages. Some of the words could do it, e.g. `co` or `pro`. Could you please check that? Thanks in advance!

**Comment by Disassembler0** [comment]
OK, will try to clean it up a little and add some other common words expected in e-mails (greetings, farewells etc.) Unfortunately the shortest words are the most used. Half of the single letters of alphabet are either prepositions or conjunctions in Czech. I'm starting to understand why the detection so hard. :)

**Comment by Disassembler0** [comment]
Amended. I've removed the clashing words, added a bunch of most frequently used words according to the Czech National Corpus and sprinkled a few words heavily used in mail communication. There are now 280 Czech words (~100 word stems).

I've run a few tests and I'm getting about 5 hits on short and poorly written mails and between 20 and 100 on half-page long mails. And 0 hits for long English, German and French articles borrowed on Wikipedia. :) I think this is the maximum I can do without delving into some heavy linguistic analysis.

**Comment by pvagner** [comment]
@Disassembler0 Shal I do something like this for slovak? What source have you used e.g. hunspell dictionary or something else?
I don't fully understand the matter but I'd be happy to make it work for me and other people writing emails in slovak.

**Pull request merged**
