### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by fatalbanana**
Ideas are to:
* get rid of dumb string matching
* try use a single instance of rspamd for whatever tests we could & [settings](https://rspamd.com/doc/configuration/settings.html) to test what we need
* try parallelise most scans with a [pre-run modifier](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#pre-run-modifier) or some other way.

### CODE REVIEW

**Comment by vstakhov** [comment]
Well, it looks good to me at the first glance but please let me know when it's ready to be merged :) Thank you!

**Comment by vstakhov** [comment]
Ping? :)

**Comment by fatalbanana** [comment]
So this is a start I suppose. 🤷 I'll look at the rest of the ideas in future PRs.

**Comment by vstakhov** [comment]
Great job, thank you very much! It looks much neater now.

**Pull request merged**
