### PR TITLE
Add bayes_expiry.conf to provide ability to set custom settings

### PR DESCRIPTION
**Pull request by dragoangel**

### CODE REVIEW

**Comment by moisseev** [comment]
In my opinion, there's no necessity to redefine module defaults. Instead, I suggest commenting parameters out and leaving them as examples.

Short comments on their meanings would be useful as well. ;)

**Comment by dragoangel** [comment]
I just do it same way I see it in other modules, it has a place in other conf. Also maybe instead of adding comments I better expand rspamd docs?

**Comment by dragoangel** [comment]
Removed settings duplication. Will create PR to docs separately

**Comment by dragoangel** [comment]
@moisseev https://github.com/rspamd/rspamd.com/pull/748 please check, if this is okay, can you approve both PRs please?

**Pull request merged**
