### PR TITLE
Support List-Id as mailing-list attribute (RFC2919) to suppress REPLY…

### LINKED ISSUE #2960: [Feature] identify mailing lists according to rfc2919 via List-Id
## Summary

REPLYTO_EQ_TO_ADDR does not support sufficient mailing-list attributes. List-Id (RFC2919) is missing.

### PR DESCRIPTION
**Pull request by wrosenauer**
…TO_EQ_TO_ADDR (fixes #2960)

### CODE REVIEW

**Comment by vstakhov** [comment]
We should probably depend on `MAILLIST` symbol instead...

**Comment by wrosenauer** [comment]
I somewhat agree but in that case I don't know how to do it.
Also is MAILLIST disabled by default? I do not see that symbol on the mailing list mails I typically receive while I would expect so.

**Comment by vstakhov** [comment]
It is enabled by default and seems to be working. I see lots of that in my messages, e.g. `MAILLIST(-0.10)[mailman];`

**Comment by wrosenauer** [comment]
Opened a bug #2964 (probably not really a bug since mlmmj seems quite flexible what headers to include and therefore it can vary quite a lot what is done outside.

**Comment by vstakhov** [comment]
This is implemented in the master branch in a different way. I'm closing this PR.

**Pull request closed without merging**
