### PR TITLE
[Fix] ezmlm mailing list software triggering MULTIPLE_UNIQUE_HEADERS by duplicate "Reply-To" header

### LINKED ISSUE #3821: [BUG] ezmlm mailing list software adds duplicate "Reply-To" header causing MULTIPLE_UNIQUE_HEADERS to trigger
The Apache Software Foundation (still) uses ezmlm  as mailing list software. I now figured out that some of the mails were classified as spam with an extra +7 score, although correctly detected as `MAILLIST` . The reason was `MULTIPLE_UNIQUE_HEADERS` triggering because one of the subscribers sent a mail (from Google Mail) with his own Reply-To header. The list was adding a second one. This is for sure a bug in ezmlm, bt this software is so old and I think it is no longer actively maintained, so we should add a composite rule to remove the bad score if it is a mailing list.

This are the mail headers:

```
[...]
Received: (qmail 42053 invoked by uid 500); 22 Jul 2021 12:22:11 -0000
Mailing-List: contact dev-help@tika.apache.org; run by ezmlm
Precedence: bulk
List-Help: <mailto:dev-help@tika.apache.org>
List-Unsubscribe: <mailto:dev-unsubscribe@tika.apache.org>
List-Post: <mailto:dev@tika.apache.org>
List-Id: <dev.tika.apache.org>
Reply-To: dev@tika.apache.org
Delivered-To: mailing list dev@tika.apache.org
Received: (qmail 42041 invoked by uid 99); 22 Jul 2021 12:22:10 -0000
Received: from mailrelay1-he-de.apache.org (HELO mailrelay1-he-de.apache.org) (116.203.21.61)
    by apache.org (qpsmtpd/0.29) with ESMTP; Thu, 22 Jul 2021 12:22:10 +0000
Received: from mail-ej1-f43.google.com (mail-ej1-f43.google.com [209.85.218.43])
	by mailrelay1-he-de.apache.org (ASF Mail Server at mailrelay1-he-de.apache.org) with ESMTPSA id 2CE673E8B0
	for <dev@tika.apache.org>; Thu, 22 Jul 2021 12:22:10 +0000 (UTC)
Received: by mail-ej1-f43.google.com with SMTP id go30so8064300ejc.8
        for <dev@tika.apache.org>; Thu, 22 Jul 2021 05:22:10 -0700 (PDT)
X-Gm-Message-State: AOAM5xxxxeE3ni6P0AWkEQ
	WC2eLrYxPSKEVHQLFCyKmRX2rAb24II6pwacah8=
X-Google-Smtp-Source: ABdhPJxg+CxxxxBNx3QWZoFVg4sjNWB7HOM=
X-Received: by 2002:a17:906:6ad2:: with SMTP id q18mr15400467ejs.107.1626956529636;
 Thu, 22 Jul 2021 05:22:09 -0700 (PDT)
MIME-Version: 1.0
Reply-To: xxx@apache.org
From: Xxx Xxxx <xxx@apache.org>
Date: Thu, 22 Jul 2021 08:21:57 -0400
X-Gmail-Original-Message-ID: <CAC1dCwX8-MAfLE4=AL4XQiSnVAQQt0=y7P7b1FojCKuC2TT+Jg@mail.gmail.com>
Message-ID: <CAC1dCwX8-MAfLE4=AL4XQiSnVAQQt0=y7P7b1FojCKuC2TT+Jg@mail.gmail.com>
Subject: JIRA...sorry
To: "<dev@tika.apache.org>" <dev@tika.apache.org>
Content-Type: text/plain; charset="UTF-8"
X-Spamd-Result: default: False [5.59 / 15.00];
	 HAS_REPLYTO(0.00)[dev@tika.apache.org];
	 RCVD_VIA_SMTP_AUTH(0.00)[];
	 R_SPF_ALLOW(-0.20)[+ip6:2a01:4f9:c010:567c::1:c];
	 MULTIPLE_UNIQUE_HEADERS(7.00)[Reply-To];
	 TO_DN_ALL(0.00)[];
	 MAILLIST(-0.10)[generic];
	 FORGED_RECIPIENTS_MAILLIST(0.00)[];
	 RCVD_TLS_LAST(0.00)[];
	 R_DKIM_NA(0.00)[];
	 ASN(0.00)[asn:24940, ipnet:2a01:4f9::/32, country:DE];
	 MIME_TRACE(0.00)[0:+];
	 FROM_NEQ_ENVFROM(0.00)[tallison@apache.org,dev-return-37675-uwe=thetaphi.de@tika.apache.org];
	 RCVD_COUNT_FIVE(0.00)[5];
	 FROM_HAS_DN(0.00)[];
	 PRECEDENCE_BULK(0.00)[];
	 MIME_GOOD(-0.10)[text/plain];
	 DMARC_NA(0.00)[apache.org];
	 FORGED_SENDER_VERP_SRS(0.00)[];
	 HAS_LIST_UNSUB(-0.01)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 RCVD_IN_DNSWL_NONE(0.00)[209.85.218.43:received];
	 RCVD_IN_DNSWL_HI(-1.00)[207.244.88.153:received,2a01:4f9:c010:567c::1:from];
	 FORGED_SENDER_MAILLIST(0.00)[];
	 GREYLIST(0.00)[pass,body]
X-Spam-Flag: YES
X-Spam-Level: *****
X-Spam-Status: Yes, score=5.59
X-Spam: Yes
```

My suggestion is to not trigger the MULTIPLE_UNIQUE_HEADERS rule, if it is a mailing list message (like we do for forged senders and similar), because this adds too much score (7!!!). I copypasted the following from composites.conf:

```
MULTIPLE_UNIQUE_HEADERS_MAILLIST {
  expression = "MULTIPLE_UNIQUE_HEADERS & -MAILLIST";
  description = "ezmlm mailing list software adds duplicate Reply-To header";
  score = 0.0;
}
```

~~My question: is it enough to paste it to composites.conf, or do I need to add the new composite symbol somewhere else? I am asking this, because it does not show up in the web interface.~~

The bug report was opened here to add the same rule to rspamd by default. I will report back and possibly may create a pull request, if it works well.

### PR DESCRIPTION
**Pull request by uschindler**
This fixes #3821

### CODE REVIEW

**Comment by uschindler** [comment]
I have no idea how to write a test, but this causes the bug: https://lists.apache.org/api/source.lua/r93f29dd737c3047cfbb083e117a826ddb6219080c578715598be146e@%3Cdev.tika.apache.org%3E

If you tell me if a test is needed, I would use this message to test.

**Comment by vstakhov** [comment]
@moisseev could you please tell your opinion about the proposed change?

**Comment by PHPGangsta** [comment]
I have one side-question: Is the problem already fixed in ezmlm? Because from an RFC point of view, having 2 "Reply-To" header is invalid. It might break existing DKIM-Signatures (if Reply-To is oversigned), and email clients might behave differently: They should show the lower one, but maybe some show the upper one.

If the problem is already fixed since a few years in ezmlm, then I would not create an exception in rspamd, but encourage the admins of old versions of ezmlm to update, to fix the problem at the source...

**Comment by moisseev** [comment]
I totally agree with @PHPGangsta . At least I wouldn't create an exception for all mailing lists.

**Comment by uschindler** [comment]
I have no idea if and how the problem was fixed in ezmlm, the mailing list software did not get any updates for long time. The source code is unreadable (heavy strcopy/strcomp C code in really old style). Apache Software Foundation seems to use latest version, but I will ask them in a moment.

I just noticed that this problem occurred many times for all EZMLM mailing lists. As the MULTIPLE_UNIQUE_HEADERS symbol has a huge score of 7, this always puts the mail into spam folder.

In general I would be happier to just say "-MAILLIST_EZMLM" in my composite rule, but there's no symbol for that.

**Comment by uschindler** [comment]
OK, I checked with Apache Infrastructure: they seem to use ezmlm-idx 7.1.1

The replytolist feature was added in 7.2 (which should work fine), so they seem to add the header in the MTA. If this is the case, I think this issue/PR can be closed, as its a misconfiguration at ASF's mail servers.

**Comment by uschindler** [comment]
OK, it works like that on their side:
- they use older ezmlm version 7.1.1 without reply to list feature
- they emulate the reply-to-list using "headeradd" in ezmlm, which produces the duplicate

They plan to upgrade at a later time. In the meantime, I will keep the composite in my local config. I would close this PR and issue.

Thanks for discussion! This is just bad as it affects the mailing lists of one of the major open source communities.

**Comment by uschindler** [comment]
Apache INFRA bug: https://issues.apache.org/jira/browse/INFRA-22141

**Comment by uschindler** [comment]
FYI,
I worked around this issue by disabling the `MULTIPLE_UNIQUE_HEADERS` just for mail coming in from apache domains:

root@serv2 /etc/rspamd/local.d # cat settings.conf
apache {
 id = "apache";
 from = "/\\bapache\\.org$/i";
 apply {
  symbols_disabled = [ "MULTIPLE_UNIQUE_HEADERS" ];
 }
}

Somebody else might be interested if affected by same problem.

**Pull request closed without merging**
