### PR TITLE
Append CXX to the list of needed languages

### PR DESCRIPTION
**Pull request by arkamar**
The `replxx` is written in C++ and it is enabled by default. We need to
specify this to correctly pass user specific `CXXFLAGS`.

### CODE REVIEW

**Comment by vstakhov** [comment]
Well, CXX is added merely if a user decided not to disable replxx. Do you experience any troubles with that?

**Comment by arkamar** [comment]
Yes, it triggers QA warning in Gentoo, See https://github.com/gentoo/gentoo/pull/13770#issuecomment-565023431. This is how configuration phase looks like without `CXX` in project languages
```
-- Cryptobox: SSE42 support is added (base64)
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C                -march=native -O2 -pipe -frecord-gcc-switches -fdiagnostics-color=always
C++               -fdiagnostics-color=always
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=gold
Module          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Shared          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=gold

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/mail-filter/rspamd-2.2/work/rspamd-2.2_build
>>> Source configured.
```
and this is with `CXX` in project languages
```
-- Cryptobox: SSE42 support is added (base64)
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C                -march=native -O2 -pipe -frecord-gcc-switches -fdiagnostics-color=always
C++              -march=native -O2 -pipe -frecord-gcc-switches -fdiagnostics-color=always
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=gold
Module          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Shared          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=gold

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/mail-filter/rspamd-2.2/work/rspamd-2.2_build
>>> Source configured
```
`CXXFLAGS` are correctly passed to the cmake and Gentoo QA is suttisfied. I can patch it in ebuild, but I believe it should be in mainstream.

**Comment by vstakhov** [comment]
OK, it actually makes my life easier :)

**Comment by arkamar** [comment]
Glad to hear that, thanks!

**Pull request merged**
